version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "@typescript-eslint/*"
          - "jest*"
          - "ts-*"
          - "tsx"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "@typescript-eslint/*"
          - "jest*"
          - "ts-*"
          - "tsx"
    labels:
      - "dependencies"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "github-actions"